---
# tasks file for dns

  - name: copy config bond to routers
    template:
      src: bond.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-bond0

  - name: copy config device bond to routers
    template:
      src: {{ item }}
      dest: /etc/sysconfig/network-scripts/ifcfg-{{ item }}
      with_fileglob:
        - bond.dev1.j2
        - bond.dev2.j2

  - name: copy config VLANond to centralRouter
    template:
      src: {{ item }}
      dest: /etc/sysconfig/network-scripts/ifcfg-{{ item }}
      with_fileglob:
        - CReth2vlan100.j2
        - CReth2vlan101.j2

  - name: restart network
    service:
      name: network
      state: restarted